context:
  version: "0.2.11"

package:
  name: rattler
  version: ${{ version }}

source:
  - url: https://github.com/conda/rattler/archive/rattler-bin-v${{ version }}.tar.gz
    sha256: 70c3f91b290bf0c5bc1eb97163f69bd828b81f453bffd9f3abed4bf810e05705
  - url: https://github.com/baszalmstra/libsolv/archive/068739980a909f39b647b9a96146e58e80741d1e.tar.gz
    target_directory: crates/rattler_libsolv_c/libsolv
    sha256: 4cf3e8a09e6710b5452be43c103aef9d33a08f31db1f5f870492045697d53161

build:
  number: 0
  script:
    env:
      # Use cmake to build aws-lc-sys, because conda's CFLAGS inject -O2 which
      # overrides the -O0 required by jitterentropy-base.c, causing a build failure.
      AWS_LC_SYS_CMAKE_BUILDER: "1"
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: unix
        then:
          - export OPENSSL_DIR=$PREFIX
      - cd crates/rattler-bin
      - cargo-bundle-licenses --format yaml --output ../../THIRDPARTY.yml
      - cargo auditable install --no-track --locked --features native-tls,s3,gcs --no-default-features --root ${{ PREFIX }} --path .
      - if: unix
        then:
          - mkdir -p $PREFIX/etc/pixi/rattler
          - touch $PREFIX/etc/pixi/rattler/global-ignore-conda-prefix
          - mkdir -p $PREFIX/share/zsh/site-functions $PREFIX/share/bash-completion/completions $PREFIX/share/fish/vendor_completions.d
          - $PREFIX/bin/rattler completion --shell zsh > $PREFIX/share/zsh/site-functions/_rattler
          - $PREFIX/bin/rattler completion --shell bash > $PREFIX/share/bash-completion/completions/rattler
          - $PREFIX/bin/rattler completion --shell fish > $PREFIX/share/fish/vendor_completions.d/rattler.fish
        else:
          - mkdir %PREFIX%\etc\pixi\rattler
          - touch %PREFIX%\etc\pixi\rattler\global-ignore-conda-prefix
requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - cmake
    - make
  host:
    - if: linux
      then:
        - openssl

tests:
  - script:
      - rattler --version
  - package_contents:
      bin:
        - rattler
      files:
        - etc/pixi/rattler/global-ignore-conda-prefix
        - if: unix
          then:
            - share/bash-completion/completions/rattler
            - share/fish/vendor_completions.d/rattler.fish
            - share/zsh/site-functions/_rattler
      strict: true

about:
  homepage: https://github.com/conda/rattler
  documentation: https://docs.rs/crate/rattler-bin
  summary: Rust binary for common Conda operations
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - crates/rattler_libsolv_c/libsolv/LICENSE.BSD
    - THIRDPARTY.yml
  repository: https://github.com/conda/rattler/tree/main/crates/rattler-bin

extra:
  recipe-maintainers:
    - baszalmstra
    - pavelzw
